update to check all package.json

diff --git a/.github/workflows/check-version.yaml b/.github/workflows/check-version.yaml
--- a/.github/workflows/check-version.yaml
+++ b/.github/workflows/check-version.yaml
@@ -22,11 +22,16 @@ jobs:
       - name: Validate Version
         if: github.event.pull_request.base.ref == 'main'
         run: |
-          version=$(jq -r '.version' package.json)
-          if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]$ ]]; then
-            echo "Invalid semver version found in package.json. Please fix the version and try again."
-            exit 1
-          else
-            echo "Valid semver version found: $version"
-            exit 0
-          fi
+          package_json_files=$(find . -name 'package.json')
+          package_json_files="$package_json_files\n./package.json"
+  
+          for package_json in $package_json_files; do
+            version=$(jq -r '.version' package.json)
+            if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]$ ]]; then
+              echo "Invalid semver version found in package.json. Please fix the version and try again."
+              exit 1
+            else
+              echo "Valid semver version found: $version"
+              exit 0
+            fi
+          done
